[tool.poetry]
name = "think-bayes"
version = "0.1.0"
description = ""
authors = ["stephan <sreindl@innitiative.at>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
